DROP TABLE IF EXISTS AUTOR;
CREATE TABLE AUTOR (
  idAutor INTEGER NOT NULL AUTO_INCREMENT  PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  telefono VARCHAR(10) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  pais VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS PRODUCTO;
CREATE TABLE PRODUCTO (
   idProducto INTEGER NOT NULL AUTO_INCREMENT  PRIMARY KEY,
   nombre VARCHAR(250) NOT NULL,
   marca VARCHAR(250) NOT NULL,
   precio number(10,2) NOT NULL
);

DROP TABLE IF EXISTS CARACTERISTICA;
CREATE TABLE CARACTERISTICA (
   idCaracteristica INTEGER NOT NULL AUTO_INCREMENT  PRIMARY KEY,
   nombre VARCHAR(250) NOT NULL,
   detalles VARCHAR(2000) NOT NULL
);

DROP TABLE IF EXISTS PRODUCTO_CARACTERISTICA;
CREATE TABLE PRODUCTO_CARACTERISTICA (
    idProducto INTEGER NOT NULL,
    idCaracteristica INTEGER NOT NULL,
    FOREIGN KEY (idProducto) REFERENCES PRODUCTO (idProducto),
    FOREIGN KEY (idCaracteristica) REFERENCES CARACTERISTICA (idCaracteristica)
);

DROP TABLE IF EXISTS REVIEW;
CREATE TABLE REVIEW (
   idReview INTEGER NOT NULL AUTO_INCREMENT  PRIMARY KEY,
   titulo VARCHAR(100) NOT NULL,
   contenido VARCHAR(2000) NOT NULL,
   idAutor INTEGER NOT NULL,
   idProducto INTEGER NOT NULL,
   FOREIGN KEY (idAutor) REFERENCES AUTOR (idAutor),
   FOREIGN KEY (idProducto) REFERENCES PRODUCTO (idProducto)
);