DROP TABLE IF EXISTS AUTOR;
CREATE TABLE AUTOR (
  id INTEGER NOT NULL AUTO_INCREMENT  PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  telefono VARCHAR(10) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  pais VARCHAR(50) NOT NULL
);